/*
* generated by Xtext
*/
package org.eclectic.frontend;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EclecticUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclectic.frontend.ui.internal.EclecticActivator.getInstance().getInjector("org.eclectic.frontend.Eclectic");
	}
	
}
