/*
* generated by Xtext
*/
package org.eclectic.frontend.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclectic.frontend.services.EclecticGrammarAccess;

public class EclecticParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EclecticGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclectic.frontend.parser.antlr.internal.InternalEclecticParser createParser(XtextTokenStream stream) {
		return new org.eclectic.frontend.parser.antlr.internal.InternalEclecticParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "EclecticTransformationDefinition";
	}
	
	public EclecticGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EclecticGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
