/*
 * generated by Xtext
 */
package org.eclectic.frontend;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ChainRuntimeModule extends org.eclectic.frontend.AbstractChainRuntimeModule {
	@Override 
	public Class<? extends org.eclipse.xtext.parser.IParser> bindIParser() {		
		return org.eclectic.frontend.ChainParserTrackingLines.class;
	}
	
}
