/*
 * generated by Xtext
 */
package org.eclectic.frontend;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TaoRuntimeModule extends org.eclectic.frontend.AbstractTaoRuntimeModule {
	/**
	 * Redefined to return a new type of parser which is able of tracking line numbers
	 * and nodes.
	 */
	@Override 
	public Class<? extends org.eclipse.xtext.parser.IParser> bindIParser() {		
		return org.eclectic.frontend.TaoParserTrackingLines.class;
	}
}
