/*
 * generated by Xtext
 */
package org.eclectic.frontend.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QoolUiModule extends org.eclectic.frontend.ui.AbstractQoolUiModule {
	public QoolUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
