/*
* generated by Xtext
*/
package org.eclectic.frontend.ui.contentassist;

import org.eclectic.frontend.ui.contentassist.AbstractChainProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ChainProposalProvider extends AbstractChainProposalProvider {

}
