/*
 * generated by Xtext
 */
package org.eclectic.streamdesc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StreamDescLanguageUiModule extends org.eclectic.streamdesc.ui.AbstractStreamDescLanguageUiModule {
	public StreamDescLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
