/*
 * generated by Xtext
 */
package org.eclectic.streamdesc.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StreamDescLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclectic.streamdesc.ui.internal.StreamDescLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.eclectic.streamdesc.ui.internal.StreamDescLanguageActivator.getInstance().getInjector("org.eclectic.streamdesc.StreamDescLanguage");
	}
	
}
