/*
 * generated by Xtext
 */
package org.eclectic.frontend.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ChainUiModule extends org.eclectic.frontend.ui.AbstractChainUiModule {
	public ChainUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
