/*
* generated by Xtext
*/
package org.eclectic.frontend.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.eclectic.frontend.services.TaoGrammarAccess;

public class TaoParser extends AbstractContentAssistParser {
	
	@Inject
	private TaoGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.eclectic.frontend.ui.contentassist.antlr.internal.InternalTaoParser createParser() {
		org.eclectic.frontend.ui.contentassist.antlr.internal.InternalTaoParser result = new org.eclectic.frontend.ui.contentassist.antlr.internal.InternalTaoParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAssignmentAccess().getAlternatives(), "rule__Assignment__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getTraceDefinitionAccess().getAlternatives_2(), "rule__TraceDefinition__Alternatives_2");
					put(grammarAccess.getPotencyAnnotationAccess().getAlternatives_0(), "rule__PotencyAnnotation__Alternatives_0");
					put(grammarAccess.getPrimaryExpressionAccess().getAlternatives(), "rule__PrimaryExpression__Alternatives");
					put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
					put(grammarAccess.getMethodCallAccess().getAlternatives_1(), "rule__MethodCall__Alternatives_1");
					put(grammarAccess.getWithResolveMethodCallAccess().getAlternatives_1(), "rule__WithResolveMethodCall__Alternatives_1");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getBinaryOpAccess().getAlternatives(), "rule__BinaryOp__Alternatives");
					put(grammarAccess.getTaoTransformationAccess().getGroup(), "rule__TaoTransformation__Group__0");
					put(grammarAccess.getTaoTransformationAccess().getGroup_4(), "rule__TaoTransformation__Group_4__0");
					put(grammarAccess.getTaoTransformationAccess().getGroup_9(), "rule__TaoTransformation__Group_9__0");
					put(grammarAccess.getUseDeclarationAccess().getGroup(), "rule__UseDeclaration__Group__0");
					put(grammarAccess.getUseDeclarationAccess().getGroup_2(), "rule__UseDeclaration__Group_2__0");
					put(grammarAccess.getTransformationDefinitionParameterAccess().getGroup(), "rule__TransformationDefinitionParameter__Group__0");
					put(grammarAccess.getClassUseAccess().getGroup(), "rule__ClassUse__Group__0");
					put(grammarAccess.getTemplateAccess().getGroup(), "rule__Template__Group__0");
					put(grammarAccess.getTemplateAccess().getGroup_4(), "rule__Template__Group_4__0");
					put(grammarAccess.getTemplateParameterAccess().getGroup(), "rule__TemplateParameter__Group__0");
					put(grammarAccess.getTemplateRootObjectAccess().getGroup(), "rule__TemplateRootObject__Group__0");
					put(grammarAccess.getTemplateRootObjectAccess().getGroup_0(), "rule__TemplateRootObject__Group_0__0");
					put(grammarAccess.getObjectInstantiationAccess().getGroup(), "rule__ObjectInstantiation__Group__0");
					put(grammarAccess.getObjectInstantiationAccess().getGroup_0(), "rule__ObjectInstantiation__Group_0__0");
					put(grammarAccess.getAttributeAssigmentAccess().getGroup(), "rule__AttributeAssigment__Group__0");
					put(grammarAccess.getWithOptionalVariableExpressionAccess().getGroup(), "rule__WithOptionalVariableExpression__Group__0");
					put(grammarAccess.getWithOptionalVariableExpressionAccess().getGroup_0(), "rule__WithOptionalVariableExpression__Group_0__0");
					put(grammarAccess.getObjectSyntaxAccess().getGroup(), "rule__ObjectSyntax__Group__0");
					put(grammarAccess.getObjectSyntaxAccess().getGroup_2(), "rule__ObjectSyntax__Group_2__0");
					put(grammarAccess.getInvocationAccess().getGroup(), "rule__Invocation__Group__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getTraceInterfaceAccess().getGroup(), "rule__TraceInterface__Group__0");
					put(grammarAccess.getTraceDefinitionAccess().getGroup(), "rule__TraceDefinition__Group__0");
					put(grammarAccess.getTraceDefinitionAccess().getGroup_2_0(), "rule__TraceDefinition__Group_2_0__0");
					put(grammarAccess.getTraceDefinitionAccess().getGroup_2_0_2(), "rule__TraceDefinition__Group_2_0_2__0");
					put(grammarAccess.getTraceDefinitionAccess().getGroup_2_1(), "rule__TraceDefinition__Group_2_1__0");
					put(grammarAccess.getTraceElementInlineAccess().getGroup(), "rule__TraceElementInline__Group__0");
					put(grammarAccess.getTraceElementExpandedAccess().getGroup(), "rule__TraceElementExpanded__Group__0");
					put(grammarAccess.getPotencyAnnotationAccess().getGroup(), "rule__PotencyAnnotation__Group__0");
					put(grammarAccess.getPropertyWriteAccess().getGroup(), "rule__PropertyWrite__Group__0");
					put(grammarAccess.getDefineVariableAccess().getGroup(), "rule__DefineVariable__Group__0");
					put(grammarAccess.getModelReferenceAccess().getGroup(), "rule__ModelReference__Group__0");
					put(grammarAccess.getParenthesizedExpressionAccess().getGroup(), "rule__ParenthesizedExpression__Group__0");
					put(grammarAccess.getClosureDeclarationAccess().getGroup(), "rule__ClosureDeclaration__Group__0");
					put(grammarAccess.getClosureDeclarationAccess().getGroup_1(), "rule__ClosureDeclaration__Group_1__0");
					put(grammarAccess.getClosureDeclarationAccess().getGroup_1_2(), "rule__ClosureDeclaration__Group_1_2__0");
					put(grammarAccess.getMethodCallAccess().getGroup(), "rule__MethodCall__Group__0");
					put(grammarAccess.getMethodCallAccess().getGroup_1_0(), "rule__MethodCall__Group_1_0__0");
					put(grammarAccess.getMethodCallAccess().getGroup_1_1(), "rule__MethodCall__Group_1_1__0");
					put(grammarAccess.getMethodCallAccess().getGroup_1_1_0(), "rule__MethodCall__Group_1_1_0__0");
					put(grammarAccess.getMethodCallAccess().getGroup_1_1_3(), "rule__MethodCall__Group_1_1_3__0");
					put(grammarAccess.getMethodCallAccess().getGroup_1_1_3_2(), "rule__MethodCall__Group_1_1_3_2__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup(), "rule__WithResolveMethodCall__Group__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_0(), "rule__WithResolveMethodCall__Group_1_0__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_1(), "rule__WithResolveMethodCall__Group_1_1__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_1_0(), "rule__WithResolveMethodCall__Group_1_1_0__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_1_0_2(), "rule__WithResolveMethodCall__Group_1_1_0_2__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_1_0_4(), "rule__WithResolveMethodCall__Group_1_1_0_4__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_1_1(), "rule__WithResolveMethodCall__Group_1_1_1__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_1_1_0(), "rule__WithResolveMethodCall__Group_1_1_1_0__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_1_1_3(), "rule__WithResolveMethodCall__Group_1_1_1_3__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_1_1_3_2(), "rule__WithResolveMethodCall__Group_1_1_1_3_2__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_2(), "rule__WithResolveMethodCall__Group_1_2__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_2_0(), "rule__WithResolveMethodCall__Group_1_2_0__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_2_0_0(), "rule__WithResolveMethodCall__Group_1_2_0_0__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_2_0_3(), "rule__WithResolveMethodCall__Group_1_2_0_3__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_2_0_3_2(), "rule__WithResolveMethodCall__Group_1_2_0_3_2__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_2_1(), "rule__WithResolveMethodCall__Group_1_2_1__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_2_1_2(), "rule__WithResolveMethodCall__Group_1_2_1_2__0");
					put(grammarAccess.getWithResolveMethodCallAccess().getGroup_1_2_1_4(), "rule__WithResolveMethodCall__Group_1_2_1_4__0");
					put(grammarAccess.getKeywordParameterAccess().getGroup(), "rule__KeywordParameter__Group__0");
					put(grammarAccess.getMatchTraceExpressionAccess().getGroup(), "rule__MatchTraceExpression__Group__0");
					put(grammarAccess.getMatchTraceExpressionAccess().getGroup_1(), "rule__MatchTraceExpression__Group_1__0");
					put(grammarAccess.getTraceExprLanguageAccess().getGroup(), "rule__TraceExprLanguage__Group__0");
					put(grammarAccess.getPutTraceExpressionAccess().getGroup(), "rule__PutTraceExpression__Group__0");
					put(grammarAccess.getPutTraceExpressionAccess().getGroup_1(), "rule__PutTraceExpression__Group_1__0");
					put(grammarAccess.getPutTraceExpressionAccess().getGroup_6(), "rule__PutTraceExpression__Group_6__0");
					put(grammarAccess.getPutTraceParameterAccess().getGroup(), "rule__PutTraceParameter__Group__0");
					put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getTaoTransformationAccess().getNameAssignment_1(), "rule__TaoTransformation__NameAssignment_1");
					put(grammarAccess.getTaoTransformationAccess().getInModelsAssignment_3(), "rule__TaoTransformation__InModelsAssignment_3");
					put(grammarAccess.getTaoTransformationAccess().getInModelsAssignment_4_1(), "rule__TaoTransformation__InModelsAssignment_4_1");
					put(grammarAccess.getTaoTransformationAccess().getOutModelsAssignment_8(), "rule__TaoTransformation__OutModelsAssignment_8");
					put(grammarAccess.getTaoTransformationAccess().getOutModelsAssignment_9_1(), "rule__TaoTransformation__OutModelsAssignment_9_1");
					put(grammarAccess.getTaoTransformationAccess().getUsesAssignment_11(), "rule__TaoTransformation__UsesAssignment_11");
					put(grammarAccess.getTaoTransformationAccess().getTemplatesAssignment_12(), "rule__TaoTransformation__TemplatesAssignment_12");
					put(grammarAccess.getUseDeclarationAccess().getModuleAssignment_1(), "rule__UseDeclaration__ModuleAssignment_1");
					put(grammarAccess.getUseDeclarationAccess().getAsAssignment_2_1(), "rule__UseDeclaration__AsAssignment_2_1");
					put(grammarAccess.getTransformationDefinitionParameterAccess().getNameAssignment_1(), "rule__TransformationDefinitionParameter__NameAssignment_1");
					put(grammarAccess.getClassUseAccess().getModelAssignment_0(), "rule__ClassUse__ModelAssignment_0");
					put(grammarAccess.getClassUseAccess().getClassNameAssignment_2(), "rule__ClassUse__ClassNameAssignment_2");
					put(grammarAccess.getTemplateAccess().getNameAssignment_1(), "rule__Template__NameAssignment_1");
					put(grammarAccess.getTemplateAccess().getParametersAssignment_3(), "rule__Template__ParametersAssignment_3");
					put(grammarAccess.getTemplateAccess().getParametersAssignment_4_1(), "rule__Template__ParametersAssignment_4_1");
					put(grammarAccess.getTemplateAccess().getRootsAssignment_6(), "rule__Template__RootsAssignment_6");
					put(grammarAccess.getTemplateParameterAccess().getNameAssignment_0(), "rule__TemplateParameter__NameAssignment_0");
					put(grammarAccess.getTemplateParameterAccess().getTypeAssignment_2(), "rule__TemplateParameter__TypeAssignment_2");
					put(grammarAccess.getTemplateRootObjectAccess().getNameAssignment_0_0(), "rule__TemplateRootObject__NameAssignment_0_0");
					put(grammarAccess.getTemplateRootObjectAccess().getTypeAssignment_1(), "rule__TemplateRootObject__TypeAssignment_1");
					put(grammarAccess.getTemplateRootObjectAccess().getAssigmentsAssignment_3(), "rule__TemplateRootObject__AssigmentsAssignment_3");
					put(grammarAccess.getObjectInstantiationAccess().getNameAssignment_0_0(), "rule__ObjectInstantiation__NameAssignment_0_0");
					put(grammarAccess.getObjectInstantiationAccess().getTypeAssignment_1(), "rule__ObjectInstantiation__TypeAssignment_1");
					put(grammarAccess.getObjectInstantiationAccess().getAssigmentsAssignment_3(), "rule__ObjectInstantiation__AssigmentsAssignment_3");
					put(grammarAccess.getAttributeAssigmentAccess().getTargetFeatureAssignment_0(), "rule__AttributeAssigment__TargetFeatureAssignment_0");
					put(grammarAccess.getAttributeAssigmentAccess().getExprAssignment_2(), "rule__AttributeAssigment__ExprAssignment_2");
					put(grammarAccess.getWithOptionalVariableExpressionAccess().getVariableAssignment_0_0(), "rule__WithOptionalVariableExpression__VariableAssignment_0_0");
					put(grammarAccess.getWithOptionalVariableExpressionAccess().getExprAssignment_1(), "rule__WithOptionalVariableExpression__ExprAssignment_1");
					put(grammarAccess.getObjectSourceVariableAccess().getNameAssignment(), "rule__ObjectSourceVariable__NameAssignment");
					put(grammarAccess.getObjectSyntaxAccess().getTargetFeatureAssignment_0(), "rule__ObjectSyntax__TargetFeatureAssignment_0");
					put(grammarAccess.getObjectSyntaxAccess().getExprAssignment_2_1(), "rule__ObjectSyntax__ExprAssignment_2_1");
					put(grammarAccess.getObjectSyntaxAccess().getMultivaluedAssignment_2_2(), "rule__ObjectSyntax__MultivaluedAssignment_2_2");
					put(grammarAccess.getObjectSyntaxAccess().getObjectAssignment_3(), "rule__ObjectSyntax__ObjectAssignment_3");
					put(grammarAccess.getInvocationAccess().getTargetFeatureAssignment_0(), "rule__Invocation__TargetFeatureAssignment_0");
					put(grammarAccess.getInvocationAccess().getTemplateAssignment_2(), "rule__Invocation__TemplateAssignment_2");
					put(grammarAccess.getInvocationAccess().getExprAssignment_4(), "rule__Invocation__ExprAssignment_4");
					put(grammarAccess.getInvocationAccess().getMultivaluedAssignment_5(), "rule__Invocation__MultivaluedAssignment_5");
					put(grammarAccess.getTraceInterfaceAccess().getNameAssignment_1(), "rule__TraceInterface__NameAssignment_1");
					put(grammarAccess.getTraceInterfaceAccess().getDefinitionsAssignment_2(), "rule__TraceInterface__DefinitionsAssignment_2");
					put(grammarAccess.getTraceDefinitionAccess().getNameAssignment_1(), "rule__TraceDefinition__NameAssignment_1");
					put(grammarAccess.getTraceDefinitionAccess().getElementsAssignment_2_0_1(), "rule__TraceDefinition__ElementsAssignment_2_0_1");
					put(grammarAccess.getTraceDefinitionAccess().getElementsAssignment_2_0_2_1(), "rule__TraceDefinition__ElementsAssignment_2_0_2_1");
					put(grammarAccess.getTraceDefinitionAccess().getElementsAssignment_2_1_0(), "rule__TraceDefinition__ElementsAssignment_2_1_0");
					put(grammarAccess.getTraceDefinitionAccess().getElementsAssignment_2_1_1(), "rule__TraceDefinition__ElementsAssignment_2_1_1");
					put(grammarAccess.getTraceElementInlineAccess().getNameAssignment_0(), "rule__TraceElementInline__NameAssignment_0");
					put(grammarAccess.getTraceElementInlineAccess().getTypeAssignment_2(), "rule__TraceElementInline__TypeAssignment_2");
					put(grammarAccess.getTraceElementExpandedAccess().getNameAssignment_1(), "rule__TraceElementExpanded__NameAssignment_1");
					put(grammarAccess.getTraceElementExpandedAccess().getTypeAssignment_3(), "rule__TraceElementExpanded__TypeAssignment_3");
					put(grammarAccess.getPotencyAnnotationAccess().getValueAssignment_1(), "rule__PotencyAnnotation__ValueAssignment_1");
					put(grammarAccess.getPropertyWriteAccess().getReceptorAssignment_0(), "rule__PropertyWrite__ReceptorAssignment_0");
					put(grammarAccess.getPropertyWriteAccess().getPropertyAssignment_2(), "rule__PropertyWrite__PropertyAssignment_2");
					put(grammarAccess.getPropertyWriteAccess().getExpressionAssignment_4(), "rule__PropertyWrite__ExpressionAssignment_4");
					put(grammarAccess.getDefineVariableAccess().getNameAssignment_0(), "rule__DefineVariable__NameAssignment_0");
					put(grammarAccess.getDefineVariableAccess().getExpressionAssignment_2(), "rule__DefineVariable__ExpressionAssignment_2");
					put(grammarAccess.getModelReferenceAccess().getModelAssignment_0(), "rule__ModelReference__ModelAssignment_0");
					put(grammarAccess.getModelReferenceAccess().getClassNameAssignment_2(), "rule__ModelReference__ClassNameAssignment_2");
					put(grammarAccess.getVariableReferenceAccess().getVariableAssignment(), "rule__VariableReference__VariableAssignment");
					put(grammarAccess.getClosureDeclarationAccess().getFormalParametersAssignment_1_1(), "rule__ClosureDeclaration__FormalParametersAssignment_1_1");
					put(grammarAccess.getClosureDeclarationAccess().getFormalParametersAssignment_1_2_1(), "rule__ClosureDeclaration__FormalParametersAssignment_1_2_1");
					put(grammarAccess.getClosureDeclarationAccess().getStatementsAssignment_2(), "rule__ClosureDeclaration__StatementsAssignment_2");
					put(grammarAccess.getClosureParameterAccess().getNameAssignment(), "rule__ClosureParameter__NameAssignment");
					put(grammarAccess.getMethodCallAccess().getBinaryOpAssignment_1_0_1(), "rule__MethodCall__BinaryOpAssignment_1_0_1");
					put(grammarAccess.getMethodCallAccess().getRightAssignment_1_0_2(), "rule__MethodCall__RightAssignment_1_0_2");
					put(grammarAccess.getMethodCallAccess().getMethodNameAssignment_1_1_2(), "rule__MethodCall__MethodNameAssignment_1_1_2");
					put(grammarAccess.getMethodCallAccess().getWithParametersAssignment_1_1_3_0(), "rule__MethodCall__WithParametersAssignment_1_1_3_0");
					put(grammarAccess.getMethodCallAccess().getParametersAssignment_1_1_3_1(), "rule__MethodCall__ParametersAssignment_1_1_3_1");
					put(grammarAccess.getMethodCallAccess().getParametersAssignment_1_1_3_2_1(), "rule__MethodCall__ParametersAssignment_1_1_3_2_1");
					put(grammarAccess.getMethodCallAccess().getParametersAssignment_1_1_4(), "rule__MethodCall__ParametersAssignment_1_1_4");
					put(grammarAccess.getWithResolveMethodCallAccess().getBinaryOpAssignment_1_0_1(), "rule__WithResolveMethodCall__BinaryOpAssignment_1_0_1");
					put(grammarAccess.getWithResolveMethodCallAccess().getRightAssignment_1_0_2(), "rule__WithResolveMethodCall__RightAssignment_1_0_2");
					put(grammarAccess.getWithResolveMethodCallAccess().getModuleAssignment_1_1_0_2_0(), "rule__WithResolveMethodCall__ModuleAssignment_1_1_0_2_0");
					put(grammarAccess.getWithResolveMethodCallAccess().getIsExternalAssignment_1_1_0_2_1(), "rule__WithResolveMethodCall__IsExternalAssignment_1_1_0_2_1");
					put(grammarAccess.getWithResolveMethodCallAccess().getLinkNameAssignment_1_1_0_3(), "rule__WithResolveMethodCall__LinkNameAssignment_1_1_0_3");
					put(grammarAccess.getWithResolveMethodCallAccess().getFeatureNameAssignment_1_1_0_4_1(), "rule__WithResolveMethodCall__FeatureNameAssignment_1_1_0_4_1");
					put(grammarAccess.getWithResolveMethodCallAccess().getMethodNameAssignment_1_1_1_2(), "rule__WithResolveMethodCall__MethodNameAssignment_1_1_1_2");
					put(grammarAccess.getWithResolveMethodCallAccess().getWithParametersAssignment_1_1_1_3_0(), "rule__WithResolveMethodCall__WithParametersAssignment_1_1_1_3_0");
					put(grammarAccess.getWithResolveMethodCallAccess().getParametersAssignment_1_1_1_3_1(), "rule__WithResolveMethodCall__ParametersAssignment_1_1_1_3_1");
					put(grammarAccess.getWithResolveMethodCallAccess().getParametersAssignment_1_1_1_3_2_1(), "rule__WithResolveMethodCall__ParametersAssignment_1_1_1_3_2_1");
					put(grammarAccess.getWithResolveMethodCallAccess().getParametersAssignment_1_1_1_4(), "rule__WithResolveMethodCall__ParametersAssignment_1_1_1_4");
					put(grammarAccess.getWithResolveMethodCallAccess().getMethodNameAssignment_1_2_0_2(), "rule__WithResolveMethodCall__MethodNameAssignment_1_2_0_2");
					put(grammarAccess.getWithResolveMethodCallAccess().getWithParametersAssignment_1_2_0_3_0(), "rule__WithResolveMethodCall__WithParametersAssignment_1_2_0_3_0");
					put(grammarAccess.getWithResolveMethodCallAccess().getParametersAssignment_1_2_0_3_1(), "rule__WithResolveMethodCall__ParametersAssignment_1_2_0_3_1");
					put(grammarAccess.getWithResolveMethodCallAccess().getParametersAssignment_1_2_0_3_2_1(), "rule__WithResolveMethodCall__ParametersAssignment_1_2_0_3_2_1");
					put(grammarAccess.getWithResolveMethodCallAccess().getParametersAssignment_1_2_0_4(), "rule__WithResolveMethodCall__ParametersAssignment_1_2_0_4");
					put(grammarAccess.getWithResolveMethodCallAccess().getModuleAssignment_1_2_1_2_0(), "rule__WithResolveMethodCall__ModuleAssignment_1_2_1_2_0");
					put(grammarAccess.getWithResolveMethodCallAccess().getIsExternalAssignment_1_2_1_2_1(), "rule__WithResolveMethodCall__IsExternalAssignment_1_2_1_2_1");
					put(grammarAccess.getWithResolveMethodCallAccess().getLinkNameAssignment_1_2_1_3(), "rule__WithResolveMethodCall__LinkNameAssignment_1_2_1_3");
					put(grammarAccess.getWithResolveMethodCallAccess().getFeatureNameAssignment_1_2_1_4_1(), "rule__WithResolveMethodCall__FeatureNameAssignment_1_2_1_4_1");
					put(grammarAccess.getKeywordParameterAccess().getKeywordAssignment_0(), "rule__KeywordParameter__KeywordAssignment_0");
					put(grammarAccess.getKeywordParameterAccess().getValueAssignment_1(), "rule__KeywordParameter__ValueAssignment_1");
					put(grammarAccess.getMatchTraceExpressionAccess().getTraceAssignment_2(), "rule__MatchTraceExpression__TraceAssignment_2");
					put(grammarAccess.getMatchTraceExpressionAccess().getTraceExprAssignment_5(), "rule__MatchTraceExpression__TraceExprAssignment_5");
					put(grammarAccess.getTraceExprLanguageAccess().getTraceVarAssignment_0(), "rule__TraceExprLanguage__TraceVarAssignment_0");
					put(grammarAccess.getTraceExprLanguageAccess().getExprAssignment_2(), "rule__TraceExprLanguage__ExprAssignment_2");
					put(grammarAccess.getPutTraceExpressionAccess().getTraceAssignment_2(), "rule__PutTraceExpression__TraceAssignment_2");
					put(grammarAccess.getPutTraceExpressionAccess().getParametersAssignment_5(), "rule__PutTraceExpression__ParametersAssignment_5");
					put(grammarAccess.getPutTraceExpressionAccess().getParametersAssignment_6_1(), "rule__PutTraceExpression__ParametersAssignment_6_1");
					put(grammarAccess.getPutTraceParameterAccess().getTraceVarAssignment_0(), "rule__PutTraceParameter__TraceVarAssignment_0");
					put(grammarAccess.getPutTraceParameterAccess().getValueAssignment_2(), "rule__PutTraceParameter__ValueAssignment_2");
					put(grammarAccess.getNumLiteralAccess().getValueAssignment(), "rule__NumLiteral__ValueAssignment");
					put(grammarAccess.getFloatLiteralAccess().getValueAssignment(), "rule__FloatLiteral__ValueAssignment");
					put(grammarAccess.getStringLiteralAccess().getValueAssignment(), "rule__StringLiteral__ValueAssignment");
					put(grammarAccess.getBooleanLiteralAccess().getValueAssignment(), "rule__BooleanLiteral__ValueAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclectic.frontend.ui.contentassist.antlr.internal.InternalTaoParser typedParser = (org.eclectic.frontend.ui.contentassist.antlr.internal.InternalTaoParser) parser;
			typedParser.entryRuleTaoTransformation();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public TaoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TaoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
