/*
 * generated by Xtext
 */
package org.eclectic.frontend.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EclecticUiModule extends org.eclectic.frontend.ui.AbstractEclecticUiModule {
	public EclecticUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
