/*
* generated by Xtext
*/
package org.eclectic.ui.contentassist;

import org.eclectic.ui.contentassist.AbstractApiDescriptionLanguageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ApiDescriptionLanguageProposalProvider extends AbstractApiDescriptionLanguageProposalProvider {

}
