/*
 * generated by Xtext
 */
package org.eclectic;

import org.eclectic.scoping.ApiDescriptionLanguageScopeProvider;
import org.eclipse.xtext.scoping.IScopeProvider;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ApiDescriptionLanguageRuntimeModule extends org.eclectic.AbstractApiDescriptionLanguageRuntimeModule {
    
	@Override
    public void configure(Binder binder) {
        super.configure(binder);
        binder
            .bind(IScopeProvider.class)
            .to(ApiDescriptionLanguageScopeProvider.class);
	}
	


}
